version: "3.3"

services:
  flaskapp:
    build:
      context: ./
      dockerfile: api.Dockerfile
    depends_on: 
      - redis
    ports:
      - "5000:5000"
    networks:
      - web_nw
        

# from your apps you can reach Redis IP with its fqdn "redis"
  redis:
      image: redis
      ports:
      - 6379:6379
      networks:
      - web_nw

networks:
  web_nw:
    driver: bridge


